using System;
using System.Collections.Generic;

namespace Application.Common.Models.DigitalSignatureModels
{
    //AUTOGENERATED
    public class ValidationPolicy
    {
        public string PolicyName { get; set; }
        public string PolicyDescription { get; set; }
    }

    public class Certificate
    {
        public string Id { get; set; }
        public string QualifiedName { get; set; }
    }

    public class CertificateChain
    {
        public List<Certificate> Certificate { get; set; }
    }

    public class SignatureLevel
    {
        public string Value { get; set; }
        public string Description { get; set; }
    }

    public class SignatureScope
    {
        public string Value { get; set; }
        public string Name { get; set; }
        public string Scope { get; set; }
    }

    public class SignatureOrTimestamp
    {
        public object Filename { get; set; }
        public CertificateChain CertificateChain { get; set; }
        public string Indication { get; set; }
        public object SubIndication { get; set; }
        public List<string> Errors { get; set; }
        public List<string> Warnings { get; set; }
        public List<object> Infos { get; set; }
        public string Id { get; set; }
        public DateTime SigningTime { get; set; }
        public DateTime BestSignatureTime { get; set; }
        public string SignedBy { get; set; }
        public SignatureLevel SignatureLevel { get; set; }
        public List<SignatureScope> SignatureScope { get; set; }
        public object CounterSignature { get; set; }
        public object ParentId { get; set; }
        public string SignatureFormat { get; set; }
        public object ExtensionPeriodMin { get; set; }
        public DateTime ExtensionPeriodMax { get; set; }
    }

    public class JaxbModel
    {
        public ValidationPolicy ValidationPolicy { get; set; }
        public string DocumentName { get; set; }
        public int ValidSignaturesCount { get; set; }
        public int SignaturesCount { get; set; }
        public object ContainerType { get; set; }
        public List<SignatureOrTimestamp> SignatureOrTimestamp { get; set; }
        public List<object> Semantic { get; set; }
        public DateTime ValidationTime { get; set; }
    }

    public class InternalVerificationResponseModel
    {
        public JaxbModel JaxbModel { get; set; }
        public DateTime ValidationTime { get; set; }
        public List<object> TimestampIdList { get; set; }
        public List<string> SignatureIdList { get; set; }
        public int SignaturesCount { get; set; }
        public object FirstTimestampId { get; set; }
        public int ValidSignaturesCount { get; set; }
        public string DocumentFilename { get; set; }
        public string FirstSignatureId { get; set; }


    }
}